import re
import json
import os
import unicodedata
from urllib.parse import quote_plus
from firebase_functions import firestore_fn, scheduler_fn, https_fn
from firebase_admin import initialize_app, firestore
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError
import pytz

# Inicializa o Admin
initialize_app()

# --- CONFIGURAÇÕES ---
ID_INSTANCE = "7107582324" 
API_TOKEN = "e3623df93ba448cc8c707e74f105a4170b0cee5a923f4a5697"     
CHAT_ID = "120363404256286081@g.us"   
SITE_URL = "https://betajulio.github.io/site-retorica/"
NEWS_URL = "https://betajulio.github.io/site-retorica/noticias.html"
PROMOTION_ADMIN_TOKEN = "retorica-force-top3-20260418"
TMDB_API_KEY = os.environ.get("TMDB_API_KEY", "326b84f0200191f182535dfc0286811c").strip()
TMDB_KEY_CACHE = {"value": None, "loaded_at": None}

LINKS_FOOTER = f"\n\n🌐 *Site:* {SITE_URL}\n🤘📰 *Notícias do Rock:* {NEWS_URL}"
try:
    SP_TZ = ZoneInfo("America/Sao_Paulo")
except ZoneInfoNotFoundError:
    SP_TZ = pytz.timezone("America/Sao_Paulo")

def now_sp():
    return datetime.now(SP_TZ)

def get_saturday_date(reference=None, include_today=False):
    ref = reference or now_sp()
    days_ahead = (5 - ref.weekday() + 7) % 7
    if days_ahead == 0 and not include_today:
        days_ahead = 7
    return (ref + timedelta(days=days_ahead)).date()

def extract_youtube_id(url):
    regex = r'(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/|youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})'
    match = re.search(regex, url)
    return match.group(1) if match else None

def get_next_saturday_str():
    return get_saturday_date(include_today=False).strftime("%d/%m")

def get_next_saturday_iso():
    return get_saturday_date(include_today=False).isoformat()

def get_current_saturday_str():
    return get_saturday_date(include_today=True).strftime("%d/%m")

def get_current_saturday_iso():
    return get_saturday_date(include_today=True).isoformat()

def is_rehearsal_cancelled(db, sat_iso):
    state_doc = db.collection("rehearsal_state").document("current").get()
    return state_doc.exists and state_doc.to_dict().get("cancelled_date") == sat_iso

def get_rehearsal_forum_doc_id(sat_iso):
    return f"rehearsal_{sat_iso}"

def ensure_rehearsal_forum(db, sat_iso, sat_str):
    existing = list(db.collection("forum").where("rehearsalDate", "==", sat_iso).limit(1).stream())
    if existing:
        return False

    db.collection("forum").document(get_rehearsal_forum_doc_id(sat_iso)).set({
        "title": f"Ensaio {sat_str} — Fórum automático",
        "date": sat_str,
        "open": True,
        "closed": False,
        "closedAt": None,
        "autoGenerated": True,
        "rehearsalDate": sat_iso,
        "createdAt": firestore.SERVER_TIMESTAMP
    })
    return True

def archive_rehearsal_forum(db, sat_iso):
    forum_docs = list(db.collection("forum").where("rehearsalDate", "==", sat_iso).stream())
    if not forum_docs:
        return 0

    batch = db.batch()
    close_count = 0
    for forum_doc in forum_docs:
        data = forum_doc.to_dict() or {}
        if data.get("closed") is True:
            continue
        batch.update(forum_doc.reference, {
            "closed": True,
            "open": False,
            "closedAt": firestore.SERVER_TIMESTAMP
        })
        close_count += 1

    if close_count:
        batch.commit()
    return close_count

def promotion_state_ref(db):
    return db.collection("promotion_state").document("current")

def to_datetime(value):
    if value is None:
        return None
    if isinstance(value, datetime):
        return value
    if hasattr(value, "to_datetime"):
        return value.to_datetime()
    if isinstance(value, str):
        try:
            return datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return None
    return None

def get_next_promotion_datetime(reference=None):
    ref = reference.astimezone(SP_TZ) if isinstance(reference, datetime) else now_sp()
    date = ref.replace(second=0, microsecond=0)
    day_of_week = date.weekday()
    days_until_friday = (4 - day_of_week + 7) % 7
    is_friday_after_cutoff = day_of_week == 4 and (
        date.hour > 23 or (date.hour == 23 and date.minute >= 59)
    )
    if days_until_friday == 0 and is_friday_after_cutoff:
        days_until_friday = 7
    target = date + timedelta(days=days_until_friday)
    return target.replace(hour=23, minute=59, second=0, microsecond=0)

def ensure_promotion_state(db):
    ref = promotion_state_ref(db)
    snap = ref.get()
    if snap.exists:
        return snap
    ref.set({
        "nextPromotionDate": get_next_promotion_datetime(),
        "activeTiebreakerPoll": None,
        "activeRepertoryPoll": None,
        "pendingRepertorySuggestionId": None,
        "completionLockToken": None,
        "completionLockUntil": None,
        "completionLockPollId": None,
        "promotionLockToken": None,
        "promotionLockUntil": None,
        "promotionPaused": False,
        "promotionPausedAt": None,
        "promotionResumedAt": None,
    })
    return ref.get()

def get_poll_snapshot_data(db, poll_id):
    if not poll_id:
        return None, False
    snap = db.collection("polls").document(str(poll_id)).get()
    return snap, snap.exists

def is_poll_closed_or_due(poll_data):
    if not poll_data:
        return False
    if poll_data.get("closed") is True:
        return True
    deadline = to_datetime(poll_data.get("deadline"))
    return bool(deadline and now_sp().astimezone(deadline.tzinfo or SP_TZ) >= deadline)

def normalize_promotion_state(db):
    state_snap = ensure_promotion_state(db)
    state = state_snap.to_dict() or {}
    updates = {}

    if "promotionPaused" not in state:
        updates["promotionPaused"] = False

    active_tiebreaker = state.get("activeTiebreakerPoll")
    _, tie_exists = get_poll_snapshot_data(db, active_tiebreaker)
    if active_tiebreaker and not tie_exists:
        updates["activeTiebreakerPoll"] = None

    active_repertory = state.get("activeRepertoryPoll")
    rep_snap, rep_exists = get_poll_snapshot_data(db, active_repertory)
    if active_repertory and not rep_exists:
        updates["activeRepertoryPoll"] = None
    elif active_repertory and rep_exists:
        rep_data = rep_snap.to_dict() or {}
        if rep_data.get("closed") is True:
            updates["activeRepertoryPoll"] = None

    pending_repertory = state.get("pendingRepertorySuggestionId")
    if pending_repertory:
        pending_snap = db.collection("suggestions").document(str(pending_repertory)).get()
        if not pending_snap.exists:
            updates["pendingRepertorySuggestionId"] = None

    if updates:
        promotion_state_ref(db).set(updates, merge=True)
        state.update(updates)

    return state

def inspect_promotion_state(db):
    state = normalize_promotion_state(db)
    tiebreaker_id = state.get("activeTiebreakerPoll")
    repertory_id = state.get("activeRepertoryPoll")
    tie_snap, tie_exists = get_poll_snapshot_data(db, tiebreaker_id)
    rep_snap, rep_exists = get_poll_snapshot_data(db, repertory_id)
    return {
        "ok": True,
        "state": state,
        "activeTiebreakerPoll": {
            "id": tiebreaker_id,
            "exists": tie_exists,
            "data": tie_snap.to_dict() if tie_exists else None
        },
        "activeRepertoryPoll": {
            "id": repertory_id,
            "exists": rep_exists,
            "data": rep_snap.to_dict() if rep_exists else None
        }
    }

def set_promotion_pause(db, paused):
    state_ref = promotion_state_ref(db)
    updates = {
        "promotionPaused": bool(paused),
    }
    if paused:
        updates["promotionPausedAt"] = firestore.SERVER_TIMESTAMP
    else:
        updates["promotionResumedAt"] = firestore.SERVER_TIMESTAMP
    state_ref.set(updates, merge=True)
    return inspect_promotion_state(db)

def get_suggestion_score(data):
    return int((data or {}).get("likes", 0) or 0) - int((data or {}).get("dislikes", 0) or 0)

def get_sorted_suggestions(db):
    def suggestion_sort_key(doc):
        data = doc.to_dict() or {}
        created_at = to_datetime(data.get("createdAt"))
        created_ts = created_at.timestamp() if isinstance(created_at, datetime) else 0
        return (
            get_suggestion_score(data),
            int(data.get("likes", 0) or 0),
            created_ts
        )

    suggestions = list(db.collection("suggestions").stream())
    return sorted(suggestions, key=suggestion_sort_key, reverse=True)

def get_top_tied_suggestions(db, limit=3):
    sorted_suggestions = get_sorted_suggestions(db)
    if not sorted_suggestions:
        return []
    top_score = get_suggestion_score(sorted_suggestions[0].to_dict() or {})
    top_candidates = [doc for doc in sorted_suggestions if get_suggestion_score(doc.to_dict() or {}) == top_score]
    return top_candidates[: min(limit, len(top_candidates))]

def create_tiebreaker_poll_backend(db, suggestion_docs):
    end_date = now_sp() + timedelta(hours=48)
    poll_ref = db.collection("polls").document()
    poll_ref.set({
        "question": "🏆 Desempate: Qual música deve ir para a enquete de repertório?",
        "options": [
            {
                "label": f"{(doc.to_dict() or {}).get('song', 'Música')} - {(doc.to_dict() or {}).get('artist', 'Artista')}",
                "votes": 0
            }
            for doc in suggestion_docs
        ],
        "createdAt": firestore.SERVER_TIMESTAMP,
        "deadline": end_date.astimezone(ZoneInfo("UTC")).isoformat(),
        "closed": False,
        "voters": [],
        "voterMap": {},
        "suggestionIds": [doc.id for doc in suggestion_docs],
        "type": "tiebreaker"
    })
    return poll_ref.id

def create_repertory_poll_backend(db, suggestion_doc):
    data = suggestion_doc.to_dict() or {}
    end_date = now_sp() + timedelta(days=7)
    poll_ref = db.collection("polls").document()
    poll_ref.set({
        "question": f"🎸 {data.get('song', 'Música')} - {data.get('artist', 'Artista')} deve entrar no repertório?",
        "options": [
            {"label": "✅ Sim, adicionar ao repertório", "votes": 0},
            {"label": "❌ Não, manter em sugestões", "votes": 0}
        ],
        "createdAt": firestore.SERVER_TIMESTAMP,
        "deadline": end_date.astimezone(ZoneInfo("UTC")).isoformat(),
        "closed": False,
        "voters": [],
        "voterMap": {},
        "suggestionId": suggestion_doc.id,
        "type": "repertory"
    })
    suggestion_doc.reference.delete()
    return poll_ref.id

def apply_repertory_poll_result(db, poll):
    options = poll.get("options", []) or []
    yes_votes = options[0].get("votes", 0) if len(options) > 0 else 0
    no_votes = options[1].get("votes", 0) if len(options) > 1 else 0
    song_and_artist = extract_repertory_poll_song(poll)
    song_title, artist = (song_and_artist.split(" - ", 1) + [""])[:2]

    if yes_votes > no_votes:
        db.collection("repertorio").document().set({
            "song": song_title.strip(),
            "artist": artist.strip(),
            "addedAt": firestore.SERVER_TIMESTAMP,
            "by": "Sistema Automático"
        })
        return "approved"

    db.collection("suggestions").document().set({
        "song": song_title.strip(),
        "artist": artist.strip(),
        "by": "Sistema",
        "createdAt": firestore.SERVER_TIMESTAMP,
        "likes": 0,
        "dislikes": 0,
        "voterMap": {}
    })
    return "rejected"

def extract_repertory_poll_song(poll):
    title = re.search(r"🎸\s*(.+?)\s*deve entrar", poll.get("question", "") or "")
    return title.group(1).strip() if title else "Música"

def build_repertory_result_message(poll):
    options = poll.get("options", []) or []
    yes_votes = int(options[0].get("votes", 0) or 0) if len(options) > 0 else 0
    no_votes = int(options[1].get("votes", 0) or 0) if len(options) > 1 else 0
    song_and_artist = extract_repertory_poll_song(poll)
    if yes_votes > no_votes:
        verdict = "✅ *APROVADA!* Entrou para o repertório."
    elif no_votes > yes_votes:
        verdict = "❌ *REPROVADA.* Voltou para sugestões."
    else:
        verdict = "⚖️ *EMPATE.* Mantida em sugestões por segurança."
    return (
        f"🏁 *ENQUETE DE REPERTÓRIO ENCERRADA!*\n\n"
        f"🎵 *Música:* {song_and_artist}\n"
        f"{verdict}\n\n"
        f"📊 *Resultado:* ✅ {yes_votes} | ❌ {no_votes}"
        f"{LINKS_FOOTER}"
    )

def get_poll_option_label(option):
    return str((option or {}).get("label") or (option or {}).get("text") or (option or {}).get("name") or "").strip()

def get_tiebreaker_label_from_suggestion(db, poll, option_index):
    suggestion_ids = poll.get("suggestionIds", []) or []
    if option_index < 0 or option_index >= len(suggestion_ids):
        return ""
    suggestion_snap = db.collection("suggestions").document(str(suggestion_ids[option_index])).get()
    if not suggestion_snap.exists:
        return ""
    data = suggestion_snap.to_dict() or {}
    song = str(data.get("song") or "").strip()
    artist = str(data.get("artist") or "").strip()
    if song and artist:
        return f"{song} - {artist}"
    return song or artist

def build_tiebreaker_result_message(db, poll):
    options = poll.get("options", []) or []
    ranked = sorted(
        enumerate(options),
        key=lambda item: int((item[1] or {}).get("votes", 0) or 0),
        reverse=True
    )
    if not ranked:
        return f"🏆 *RESULTADO DO DESEMPATE*\n\nNenhuma opção encontrada.{LINKS_FOOTER}"

    winner_index, winner_option = ranked[0]
    winner = str(poll.get("winnerLabel") or "").strip()
    if not winner:
        winner = get_poll_option_label(winner_option)
    if not winner:
        winner = get_tiebreaker_label_from_suggestion(db, poll, winner_index)
    if not winner:
        winner = "Música vencedora não identificada"

    losers = []
    for option_index, option in ranked[1:]:
        label = get_poll_option_label(option) or get_tiebreaker_label_from_suggestion(db, poll, option_index) or "Música"
        votes = int((option or {}).get("votes", 0) or 0)
        losers.append(f"{label} ({votes} votos)")
    losers_text = "\n".join(losers) if losers else "Sem perdedoras."

    return (
        f"🏆 *RESULTADO DO DESEMPATE*\n\n"
        f"🎵 *Música vencedora:*\n{winner}\n\n"
        f"❌ *Perderam:*\n{losers_text}"
        f"{LINKS_FOOTER}"
    )

def process_due_repertory_poll_doc(db, poll_doc):
    poll = poll_doc.to_dict() or {}
    deadline = to_datetime(poll.get("deadline"))
    if poll.get("closed") is True or not deadline or now_sp().astimezone(deadline.tzinfo or SP_TZ) < deadline:
        return None

    poll_doc.reference.set({"closed": True}, merge=True)
    result = apply_repertory_poll_result(db, poll)
    return {"pollId": poll_doc.id, "result": result}

def process_due_repertory_polls(db):
    completed = []
    for poll_doc in db.collection("polls").where("type", "==", "repertory").where("closed", "==", False).stream():
        result = process_due_repertory_poll_doc(db, poll_doc)
        if result:
            completed.append(result)

    if not completed:
        return []

    state = normalize_promotion_state(db)
    active_repertory = state.get("activeRepertoryPoll")
    if active_repertory and any(item["pollId"] == active_repertory for item in completed):
        promotion_state_ref(db).set({
            "activeRepertoryPoll": None,
            "nextPromotionDate": get_next_promotion_datetime()
        }, merge=True)
    return completed

def activate_or_queue_repertory_poll(db, suggestion_doc):
    state = normalize_promotion_state(db)
    state_ref = promotion_state_ref(db)

    active_repertory = state.get("activeRepertoryPoll")
    if active_repertory:
        rep_snap, rep_exists = get_poll_snapshot_data(db, active_repertory)
        rep_data = rep_snap.to_dict() if rep_exists else None
        if (not rep_exists) or is_poll_closed_or_due(rep_data):
            process_repertory_completion(db)
            state = normalize_promotion_state(db)
            active_repertory = state.get("activeRepertoryPoll")

    poll_id = create_repertory_poll_backend(db, suggestion_doc)
    updates = {"pendingRepertorySuggestionId": None}
    if not active_repertory:
        updates["activeRepertoryPoll"] = poll_id
    state_ref.set(updates, merge=True)
    return {
        "status": "created",
        "pollId": poll_id,
        "suggestionId": suggestion_doc.id
    }

def process_pending_repertory_poll(db):
    state = normalize_promotion_state(db)

    pending_suggestion_id = state.get("pendingRepertorySuggestionId")
    if not pending_suggestion_id:
        return None

    state_ref = promotion_state_ref(db)
    pending_ref = db.collection("suggestions").document(str(pending_suggestion_id))
    pending_snap = pending_ref.get()
    if not pending_snap.exists:
        state_ref.set({"pendingRepertorySuggestionId": None}, merge=True)
        return {"status": "cleared_missing", "suggestionId": str(pending_suggestion_id)}

    poll_id = create_repertory_poll_backend(db, pending_snap)
    updates = {"pendingRepertorySuggestionId": None}
    if not state.get("activeRepertoryPoll"):
        updates["activeRepertoryPoll"] = poll_id
    state_ref.set(updates, merge=True)
    print(f"Enquete de repertório pendente ativada automaticamente: {poll_id}")
    return {"status": "created", "pollId": poll_id, "suggestionId": str(pending_suggestion_id)}

def advance_promotion_pipeline(db):
    completed_repertory_polls = process_due_repertory_polls(db)
    process_repertory_completion(db)
    pending_before_tie = process_pending_repertory_poll(db)
    process_tiebreaker_completion(db)
    pending_after_tie = process_pending_repertory_poll(db)
    process_due_promotion(db)
    return {
        "ok": True,
        "completedRepertoryPolls": completed_repertory_polls,
        "pendingBeforeTiebreaker": pending_before_tie,
        "pendingAfterTiebreaker": pending_after_tie,
        "state": normalize_promotion_state(db)
    }

def clear_current_setlist(db):
    setlist_ref = db.collection("setlists").document("data")
    setlist_snap = setlist_ref.get()
    current_songs = []
    if setlist_snap.exists:
        current_songs = (setlist_snap.to_dict() or {}).get("tab0", []) or []
        setlist_ref.set({"tab0": []}, merge=True)
    else:
        setlist_ref.set({"tab0": [], "tab1": []}, merge=True)
    return {
        "ok": True,
        "removedCount": len(current_songs),
        "removedSongs": [
            {
                "song": (song or {}).get("song", ""),
                "artist": (song or {}).get("artist", "")
            }
            for song in current_songs
        ]
    }

def process_due_promotion(db):
    state = normalize_promotion_state(db)
    state_ref = promotion_state_ref(db)
    now_local = now_sp()
    next_promotion = to_datetime(state.get("nextPromotionDate"))

    if state.get("promotionPaused") is True:
        return
    if next_promotion and next_promotion.astimezone(SP_TZ) > now_local:
        return
    if state.get("pendingRepertorySuggestionId"):
        process_pending_repertory_poll(db)
        return
    if state.get("activeTiebreakerPoll") or state.get("pendingRepertorySuggestionId"):
        return

    suggestions = list(db.collection("suggestions").stream())
    if not suggestions:
        state_ref.set({"nextPromotionDate": get_next_promotion_datetime(now_local)}, merge=True)
        return

    sorted_suggestions = sorted(
        suggestions,
        key=lambda doc: (
            get_suggestion_score(doc.to_dict() or {}),
            int((doc.to_dict() or {}).get("likes", 0) or 0)
        ),
        reverse=True
    )
    top_score = get_suggestion_score(sorted_suggestions[0].to_dict() or {})
    top_candidates = [doc for doc in sorted_suggestions if get_suggestion_score(doc.to_dict() or {}) == top_score]

    if len(top_candidates) >= 2:
        poll_id = create_tiebreaker_poll_backend(db, top_candidates[: min(3, len(top_candidates))])
        state_ref.set({
            "activeTiebreakerPoll": poll_id,
            "nextPromotionDate": get_next_promotion_datetime(now_local)
        }, merge=True)
        print(f"Desempate criado automaticamente: {poll_id}")
        return

    repertory_result = activate_or_queue_repertory_poll(db, top_candidates[0])
    state_ref.set({
        "nextPromotionDate": get_next_promotion_datetime(now_local)
    }, merge=True)
    if repertory_result["status"] == "created":
        print(f"Enquete de repertório criada automaticamente: {repertory_result['pollId']}")
    else:
        print(f"Enquete de repertório enfileirada automaticamente para a sugestão: {repertory_result['suggestionId']}")

def force_create_top3_tiebreaker(db):
    state = normalize_promotion_state(db)
    state_ref = promotion_state_ref(db)

    if state.get("activeTiebreakerPoll") or state.get("pendingRepertorySuggestionId"):
        return {
            "ok": False,
            "error": "Já existe um desempate ativo ou uma enquete de repertório pendente na fila.",
            "activeTiebreakerPoll": state.get("activeTiebreakerPoll"),
            "activeRepertoryPoll": state.get("activeRepertoryPoll"),
            "pendingRepertorySuggestionId": state.get("pendingRepertorySuggestionId"),
        }

    selected = get_top_tied_suggestions(db, 3)
    if len(selected) < 2:
        return {"ok": False, "error": "Menos de duas sugestões disponíveis para desempate."}
    poll_id = create_tiebreaker_poll_backend(db, selected)
    state_ref.set({"activeTiebreakerPoll": poll_id}, merge=True)
    return {
        "ok": True,
        "pollId": poll_id,
        "activeRepertoryPoll": state.get("activeRepertoryPoll"),
        "songs": [
            {
                "id": doc.id,
                "song": (doc.to_dict() or {}).get("song", ""),
                "artist": (doc.to_dict() or {}).get("artist", ""),
                "score": get_suggestion_score(doc.to_dict() or {}),
                "likes": int((doc.to_dict() or {}).get("likes", 0) or 0)
            }
            for doc in selected
        ]
    }

def refresh_active_tiebreaker_from_ties(db):
    state = normalize_promotion_state(db)
    poll_id = state.get("activeTiebreakerPoll")
    if not poll_id:
        return {"ok": False, "error": "Nenhuma enquete de desempate ativa."}

    poll_ref = db.collection("polls").document(str(poll_id))
    poll_snap = poll_ref.get()
    if not poll_snap.exists:
        promotion_state_ref(db).set({"activeTiebreakerPoll": None}, merge=True)
        return {"ok": False, "error": "A enquete de desempate ativa não foi encontrada."}

    poll = poll_snap.to_dict() or {}
    options = poll.get("options", []) or []
    voters = poll.get("voters", []) or []
    voter_map = poll.get("voterMap", {}) or {}
    total_votes = sum(int((opt or {}).get("votes", 0) or 0) for opt in options)
    if total_votes > 0 or voters or voter_map:
        return {"ok": False, "error": "A enquete de desempate já possui votos e não pode ser reordenada automaticamente."}

    selected = get_top_tied_suggestions(db, 3)
    if len(selected) < 2:
        return {"ok": False, "error": "Não há sugestões empatadas suficientes para montar o desempate."}

    new_options = [
        {
            "label": f"{(doc.to_dict() or {}).get('song', 'Música')} - {(doc.to_dict() or {}).get('artist', 'Artista')}",
            "votes": 0
        }
        for doc in selected
    ]
    new_ids = [doc.id for doc in selected]
    poll_ref.set({
        "options": new_options,
        "suggestionIds": new_ids
    }, merge=True)
    return {
        "ok": True,
        "pollId": poll_id,
        "songs": [
            {
                "id": doc.id,
                "song": (doc.to_dict() or {}).get("song", ""),
                "artist": (doc.to_dict() or {}).get("artist", ""),
                "score": get_suggestion_score(doc.to_dict() or {}),
                "likes": int((doc.to_dict() or {}).get("likes", 0) or 0)
            }
            for doc in selected
        ]
    }

def process_tiebreaker_completion(db):
    state = normalize_promotion_state(db)
    poll_id = state.get("activeTiebreakerPoll")
    if not poll_id:
        return

    state_ref = promotion_state_ref(db)
    poll_ref = db.collection("polls").document(poll_id)
    poll_snap = poll_ref.get()
    if not poll_snap.exists:
        state_ref.set({"activeTiebreakerPoll": None}, merge=True)
        return

    poll = poll_snap.to_dict() or {}
    deadline = to_datetime(poll.get("deadline"))
    if poll.get("closed") is True or not deadline or now_sp().astimezone(deadline.tzinfo or SP_TZ) < deadline:
        return

    options = poll.get("options", []) or []
    if not options:
        poll_ref.set({"closed": True}, merge=True)
        state_ref.set({"activeTiebreakerPoll": None, "nextPromotionDate": get_next_promotion_datetime()}, merge=True)
        return

    max_votes = max((opt.get("votes", 0) or 0) for opt in options)
    winner_idx = next((idx for idx, opt in enumerate(options) if (opt.get("votes", 0) or 0) == max_votes), None)
    suggestion_ids = poll.get("suggestionIds", []) or []
    if winner_idx is None or winner_idx >= len(suggestion_ids):
        poll_ref.set({"closed": True}, merge=True)
        state_ref.set({"activeTiebreakerPoll": None, "nextPromotionDate": get_next_promotion_datetime()}, merge=True)
        return

    suggestion_ref = db.collection("suggestions").document(suggestion_ids[winner_idx])
    suggestion_snap = suggestion_ref.get()
    winner_label = get_poll_option_label(options[winner_idx]) or (
        f"{(suggestion_snap.to_dict() or {}).get('song', '')} - {(suggestion_snap.to_dict() or {}).get('artist', '')}".strip(" -")
        if suggestion_snap.exists else ""
    )
    poll_ref.set({"closed": True, "winnerLabel": winner_label}, merge=True)

    if not suggestion_snap.exists:
        state_ref.set({"activeTiebreakerPoll": None, "nextPromotionDate": get_next_promotion_datetime()}, merge=True)
        return

    repertory_result = activate_or_queue_repertory_poll(db, suggestion_snap)
    if repertory_result["status"] == "created":
        state_ref.set({
            "activeTiebreakerPoll": None
        }, merge=True)
        print(f"Desempate concluído automaticamente; enquete de repertório criada: {repertory_result['pollId']}")
        return

    state_ref.set({
        "activeTiebreakerPoll": None,
        "pendingRepertorySuggestionId": suggestion_snap.id
    }, merge=True)
    print(f"Desempate concluído automaticamente; sugestão enfileirada para repertório: {suggestion_snap.id}")

def process_repertory_completion(db):
    state = normalize_promotion_state(db)
    poll_id = state.get("activeRepertoryPoll")
    if not poll_id:
        return

    state_ref = promotion_state_ref(db)
    poll_ref = db.collection("polls").document(poll_id)
    poll_snap = poll_ref.get()
    if not poll_snap.exists:
        state_ref.set({"activeRepertoryPoll": None, "nextPromotionDate": get_next_promotion_datetime()}, merge=True)
        return

    poll = poll_snap.to_dict() or {}
    deadline = to_datetime(poll.get("deadline"))
    if poll.get("closed") is True or not deadline or now_sp().astimezone(deadline.tzinfo or SP_TZ) < deadline:
        return

    poll_ref.set({"closed": True}, merge=True)
    apply_repertory_poll_result(db, poll)

    pending_suggestion_id = state.get("pendingRepertorySuggestionId")
    if pending_suggestion_id:
        pending_ref = db.collection("suggestions").document(str(pending_suggestion_id))
        pending_snap = pending_ref.get()
        if pending_snap.exists:
            state_ref.set({
                "activeRepertoryPoll": None
            }, merge=True)
            queued_result = activate_or_queue_repertory_poll(db, pending_snap)
            state_ref.set({
                "activeRepertoryPoll": queued_result.get("pollId"),
                "pendingRepertorySuggestionId": None,
                "nextPromotionDate": get_next_promotion_datetime()
            }, merge=True)
            print(f"Enquete de repertório concluída; próxima enquete de repertório ativada: {queued_result.get('pollId')}")
            return

        state_ref.set({
            "pendingRepertorySuggestionId": None
        }, merge=True)

    state_ref.set({
        "activeRepertoryPoll": None,
        "nextPromotionDate": get_next_promotion_datetime()
    }, merge=True)
    print(f"Enquete de repertório concluída automaticamente: {poll_id}")

def slugify_text(value):
    normalized = unicodedata.normalize("NFKD", value or "")
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", ascii_text.lower()).strip("-")
    return slug

def json_response(payload, status=200):
    resp = https_fn.Response(
        response=json.dumps(payload, ensure_ascii=False, default=str),
        status=status,
        mimetype="application/json",
    )
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Access-Control-Allow-Methods"] = "GET,OPTIONS"
    resp.headers["Access-Control-Allow-Headers"] = "Content-Type"
    return resp

def update_log_delivery_status(db, log_id, status, detail):
    if not log_id:
        return
    db.collection("logs").document(log_id).set({
        "whatsAppStatus": status,
        "whatsAppDetail": detail,
        "processedAt": firestore.SERVER_TIMESTAMP
    }, merge=True)

def format_gallery_item_date(data):
    explicit_date = (data or {}).get("date")
    if explicit_date:
        return str(explicit_date)
    created_at = (data or {}).get("createdAt")
    if hasattr(created_at, "astimezone"):
        try:
            return created_at.astimezone(SP_TZ).strftime("%d/%m/%Y")
        except Exception:
            return None
    return None

def extract_first_youtube_url(song, artist):
    import requests
    queries = [
        f"{song} {artist} official audio".strip(),
        f"{song} {artist}".strip(),
    ]
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                      "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    }
    for query in queries:
        response = requests.get(
            "https://www.youtube.com/results",
            params={"search_query": query},
            headers=headers,
            timeout=15,
        )
        ids = re.findall(r'"videoId":"([A-Za-z0-9_-]{11})"', response.text)
        seen = []
        for video_id in ids:
            if video_id not in seen:
                seen.append(video_id)
        if seen:
            return f"https://www.youtube.com/watch?v={seen[0]}"
    return None

def normalize_image_url(url):
    if not url:
        return ""
    if url.startswith("//"):
        return f"https:{url}"
    return url.replace("http://", "https://")

def build_google_search_url(query):
    return f"https://www.google.com/search?q={quote_plus(query)}"

def get_tmdb_api_key():
    if TMDB_API_KEY:
        return TMDB_API_KEY

    now = datetime.utcnow()
    cached_at = TMDB_KEY_CACHE.get("loaded_at")
    if cached_at and TMDB_KEY_CACHE.get("value") is not None and (now - cached_at).total_seconds() < 300:
        return TMDB_KEY_CACHE.get("value") or ""

    try:
        db = firestore.client()
        snap = db.collection("config").document("api_keys").get()
        value = ""
        if snap.exists:
            data = snap.to_dict() or {}
            value = str(data.get("tmdbApiKey") or "").strip()
        TMDB_KEY_CACHE["value"] = value
        TMDB_KEY_CACHE["loaded_at"] = now
        return value
    except Exception:
        TMDB_KEY_CACHE["value"] = ""
        TMDB_KEY_CACHE["loaded_at"] = now
        return ""

def lookup_music_recommendation(query):
    url = extract_first_youtube_url(query, "")
    if not url:
        return {
            "ok": True,
            "title": query,
            "thumbUrl": "",
            "sourceUrl": build_google_search_url(f"{query} youtube"),
            "sourceLabel": "Busca YouTube"
        }
    video_id = extract_youtube_id(url)
    return {
        "ok": True,
        "title": query,
        "thumbUrl": f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg" if video_id else "",
        "sourceUrl": url,
        "sourceLabel": "YouTube"
    }

def lookup_book_recommendation(query):
    import requests
    try:
        response = requests.get(
            "https://www.googleapis.com/books/v1/volumes",
            params={"q": query, "maxResults": 1, "printType": "books"},
            timeout=15,
        )
        response.raise_for_status()
        payload = response.json() or {}
        items = payload.get("items") or []
        if items:
            info = (items[0] or {}).get("volumeInfo") or {}
            image_links = info.get("imageLinks") or {}
            return {
                "ok": True,
                "title": info.get("title") or query,
                "thumbUrl": normalize_image_url(image_links.get("thumbnail") or image_links.get("smallThumbnail") or ""),
                "sourceUrl": info.get("infoLink") or build_google_search_url(f"{query} livro"),
                "sourceLabel": "Google Books"
            }
    except Exception as exc:
        print(f"Google Books lookup failed for {query}: {type(exc).__name__}: {exc}")

    try:
        response = requests.get(
            "https://openlibrary.org/search.json",
            params={"title": query, "limit": 1, "fields": "key,title,cover_i"},
            timeout=15,
        )
        response.raise_for_status()
        payload = response.json() or {}
        docs = payload.get("docs") or []
        if docs:
            book = docs[0] or {}
            cover_id = book.get("cover_i")
            source_key = book.get("key") or ""
            return {
                "ok": True,
                "title": book.get("title") or query,
                "thumbUrl": f"https://covers.openlibrary.org/b/id/{cover_id}-M.jpg" if cover_id else "",
                "sourceUrl": f"https://openlibrary.org{source_key}" if source_key else build_google_search_url(f"{query} livro"),
                "sourceLabel": "Open Library"
            }
    except Exception as exc:
        print(f"Open Library lookup failed for {query}: {type(exc).__name__}: {exc}")

    return {
        "ok": True,
        "title": query,
        "thumbUrl": "",
        "sourceUrl": build_google_search_url(f"{query} livro"),
        "sourceLabel": "Busca Google"
    }

def lookup_tmdb_recommendation(query, media_type):
    import requests
    tmdb_api_key = get_tmdb_api_key()
    if not tmdb_api_key:
        return {
            "ok": True,
            "title": query,
            "thumbUrl": "",
            "sourceUrl": build_google_search_url(f"{query} {media_type}"),
            "sourceLabel": "Busca Google",
            "pendingConfig": True
        }

    endpoint = "tv" if media_type == "series" else "movie"
    response = requests.get(
        f"https://api.themoviedb.org/3/search/{endpoint}",
        params={
            "api_key": tmdb_api_key,
            "language": "pt-BR",
            "query": query,
            "include_adult": "false",
        },
        timeout=15,
    )
    response.raise_for_status()
    payload = response.json() or {}
    results = payload.get("results") or []
    if not results:
        return {
            "ok": True,
            "title": query,
            "thumbUrl": "",
            "sourceUrl": build_google_search_url(f"{query} {media_type}"),
            "sourceLabel": "TMDb"
        }
    item = results[0] or {}
    title = item.get("title") or item.get("name") or query
    poster = item.get("poster_path") or ""
    source_path = f"/movie/{item.get('id')}" if endpoint == "movie" else f"/tv/{item.get('id')}"
    return {
        "ok": True,
        "title": title,
        "thumbUrl": f"https://image.tmdb.org/t/p/w342{poster}" if poster else "",
        "sourceUrl": f"https://www.themoviedb.org{source_path}",
        "sourceLabel": "TMDb"
    }

def build_cifra_candidates(song, artist):
    song_slug = slugify_text(song)
    artist_slug = slugify_text(artist)
    base_song_url = f"https://www.cifraclub.com.br/{artist_slug}/{song_slug}/" if artist_slug and song_slug else ""
    candidates = []
    if base_song_url:
        candidates.append({"label": "Cifra Club principal", "url": base_song_url})
        candidates.append({"label": "Cifra Club simplificada", "url": f"{base_song_url}simplificada.html"})
    if artist_slug:
        candidates.append({"label": "Página do artista no Cifra Club", "url": f"https://www.cifraclub.com.br/{artist_slug}/"})
    search_term = quote_plus(f"{song} {artist} cifra")
    candidates.append({"label": "Busca Google por cifra", "url": f"https://www.google.com/search?q={search_term}"})
    return candidates

@https_fn.on_request()
def lookup_youtube_link(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    if req.method != "GET":
        return json_response({"ok": False, "error": "Método não suportado"}, 405)

    song = (req.args.get("song") or "").strip()
    artist = (req.args.get("artist") or "").strip()
    if not song:
        return json_response({"ok": False, "error": "Parâmetro song é obrigatório"}, 400)

    try:
        url = extract_first_youtube_url(song, artist)
    except Exception as exc:
        return json_response({"ok": False, "error": f"Falha ao buscar vídeo: {exc}"}, 500)

    if not url:
        return json_response({"ok": False, "error": "Nenhum vídeo encontrado"}, 404)

    return json_response({"ok": True, "url": url})

@https_fn.on_request()
def lookup_cifra_candidates(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    if req.method != "GET":
        return json_response({"ok": False, "error": "Método não suportado"}, 405)

    song = (req.args.get("song") or "").strip()
    artist = (req.args.get("artist") or "").strip()
    if not song:
        return json_response({"ok": False, "error": "Parâmetro song é obrigatório"}, 400)

    candidates = build_cifra_candidates(song, artist)
    return json_response({"ok": True, "candidates": candidates})

@https_fn.on_request()
def lookup_member_recommendation(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    if req.method != "GET":
        return json_response({"ok": False, "error": "Método não suportado"}, 405)

    category = (req.args.get("category") or "").strip().lower()
    query = (req.args.get("query") or "").strip()
    if not category:
        return json_response({"ok": False, "error": "Parâmetro category é obrigatório"}, 400)
    if not query:
        return json_response({"ok": False, "error": "Parâmetro query é obrigatório"}, 400)

    try:
        if category == "music":
            payload = lookup_music_recommendation(query)
        elif category == "books":
            payload = lookup_book_recommendation(query)
        elif category in ("movies", "series"):
            payload = lookup_tmdb_recommendation(query, category)
        else:
            return json_response({"ok": False, "error": "Categoria não suportada"}, 400)
    except Exception as exc:
        return json_response({"ok": False, "error": f"Falha ao buscar recomendação: {exc}"}, 500)

    payload["category"] = category
    payload["query"] = query
    return json_response(payload)

@https_fn.on_request()
def admin_force_tiebreaker_top3(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    token = (req.args.get("token") or req.headers.get("x-admin-token") or "").strip()
    if token != PROMOTION_ADMIN_TOKEN:
        return json_response({"ok": False, "error": "unauthorized"}, 403)

    db = firestore.client()
    try:
        result = force_create_top3_tiebreaker(db)
        return json_response(result, 200 if result.get("ok") else 409)
    except Exception as exc:
        return json_response({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)

@https_fn.on_request()
def admin_inspect_promotion(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    token = (req.args.get("token") or req.headers.get("x-admin-token") or "").strip()
    if token != PROMOTION_ADMIN_TOKEN:
        return json_response({"ok": False, "error": "unauthorized"}, 403)

    db = firestore.client()
    try:
        result = inspect_promotion_state(db)
        return json_response(result, 200)
    except Exception as exc:
        return json_response({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)

@https_fn.on_request()
def admin_set_promotion_pause(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    token = (req.args.get("token") or req.headers.get("x-admin-token") or "").strip()
    if token != PROMOTION_ADMIN_TOKEN:
        return json_response({"ok": False, "error": "unauthorized"}, 403)

    raw_paused = (req.args.get("paused") or "").strip().lower()
    if raw_paused not in ("true", "false", "1", "0", "yes", "no"):
        return json_response({"ok": False, "error": "Parâmetro paused deve ser true ou false."}, 400)

    db = firestore.client()
    try:
        result = set_promotion_pause(db, raw_paused in ("true", "1", "yes"))
        return json_response(result, 200)
    except Exception as exc:
        return json_response({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)

@https_fn.on_request()
def admin_refresh_active_tiebreaker(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    token = (req.args.get("token") or req.headers.get("x-admin-token") or "").strip()
    if token != PROMOTION_ADMIN_TOKEN:
        return json_response({"ok": False, "error": "unauthorized"}, 403)

    db = firestore.client()
    try:
        result = refresh_active_tiebreaker_from_ties(db)
        return json_response(result, 200 if result.get("ok") else 409)
    except Exception as exc:
        return json_response({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)

@https_fn.on_request()
def admin_advance_promotion(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    token = (req.args.get("token") or req.headers.get("x-admin-token") or "").strip()
    if token != PROMOTION_ADMIN_TOKEN:
        return json_response({"ok": False, "error": "unauthorized"}, 403)

    db = firestore.client()
    try:
        result = advance_promotion_pipeline(db)
        return json_response(result, 200)
    except Exception as exc:
        return json_response({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)

@https_fn.on_request()
def admin_clear_current_setlist(req: https_fn.Request) -> https_fn.Response:
    if req.method == "OPTIONS":
        return json_response({}, 204)
    token = (req.args.get("token") or req.headers.get("x-admin-token") or "").strip()
    if token != PROMOTION_ADMIN_TOKEN:
        return json_response({"ok": False, "error": "unauthorized"}, 403)

    db = firestore.client()
    try:
        result = clear_current_setlist(db)
        return json_response(result, 200)
    except Exception as exc:
        return json_response({"ok": False, "error": f"{type(exc).__name__}: {exc}"}, 500)

def send_wa_message(text):
    import requests
    url = f"https://api.green-api.com/waInstance{ID_INSTANCE}/sendMessage/{API_TOKEN}"
    payload = {"chatId": CHAT_ID, "message": text}
    try:
        resp = requests.post(url, json=payload, timeout=10)
        raw_body = (resp.text or "").strip()
        if not resp.ok:
            return {"ok": False, "detail": f"HTTP {resp.status_code}: {raw_body[:300]}"}
        try:
            data = resp.json()
        except ValueError:
            data = {}
        if isinstance(data, dict) and data.get("error"):
            return {"ok": False, "detail": str(data.get("error"))[:300]}
        message_id = data.get("idMessage") if isinstance(data, dict) else None
        return {"ok": True, "detail": f"idMessage={message_id}" if message_id else "Mensagem aceita pelo provedor"}
    except Exception as exc:
        return {"ok": False, "detail": f"{type(exc).__name__}: {exc}"[:300]}

def send_wa_image(file_url, caption):
    import requests
    url = f"https://api.green-api.com/waInstance{ID_INSTANCE}/sendFileByUrl/{API_TOKEN}"
    payload = {"chatId": CHAT_ID, "urlFile": file_url, "fileName": "foto.jpg", "caption": caption}
    try:
        resp = requests.post(url, json=payload, timeout=15)
        raw_body = (resp.text or "").strip()
        if not resp.ok:
            return {"ok": False, "detail": f"HTTP {resp.status_code}: {raw_body[:300]}"}
        return {"ok": True, "detail": "Imagem aceita pelo provedor"}
    except Exception as exc:
        return {"ok": False, "detail": f"{type(exc).__name__}: {exc}"[:300]}

# 1. GATILHO: NOVA ENQUETE
@firestore_fn.on_document_created(document="polls/{pollId}")
def on_poll_created(event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None]) -> None:
    poll = event.data.to_dict()
    if poll:
        q = poll.get('question', 'Nova Enquete')
        d = poll.get('description', '')
        opts = poll.get('options', [])
        opts_txt = "\n" + "\n".join([f"🔹 {o.get('label')}" for o in opts]) if opts else ""
        desc_txt = f"\n📝 _{d}_" if d else ""
        send_wa_message(f"🗳️ *NOVA ENQUETE NO AR!*\n\n❓ *{q}*{desc_txt}\n{opts_txt}{LINKS_FOOTER}")

# 2. GATILHO: NOVAS FOTOS
@firestore_fn.on_document_created(document="gallery/{photoId}")
def on_photo_added(event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None]) -> None:
    p = event.data.to_dict()
    if p:
        media_type = p.get('mediaType', 'image')
        caption_db = p.get('caption', '')
        youtube_title = str(p.get('youtubeTitle', '') or '').strip()
        tags_db = p.get('tags', []) or []
        real_tags = [tag for tag in tags_db if tag and tag != 'Todas']
        tag_db = real_tags[0] if real_tags else p.get('tag', 'Bastidores')
        user_name = p.get('addedBy', 'Membro')
        item_date = format_gallery_item_date(p)
        desc_txt = f"📝 _{caption_db}_\n\n" if caption_db else ""
        date_txt = f"\n🗓️ Data: *{item_date}*" if item_date else ""
        if media_type == 'youtube':
            video_url = p.get('url', '')
            title_txt = f"🎵 *Música:* {youtube_title}\n" if youtube_title else ""
            video_txt = f"\n🎬 *Assistir:* {video_url}" if video_url else ""
            msg = f"{title_txt}{desc_txt}🎥 *Novo vídeo na galeria!* [#{tag_db}]\n👤 Enviado por: *{user_name}*{date_txt}{video_txt}{LINKS_FOOTER}"
            if p.get('thumbUrl'):
                send_wa_image(p['thumbUrl'], msg)
            else:
                send_wa_message(msg)
        else:
            msg = f"{desc_txt}📸 *Nova foto na galeria!* [#{tag_db}]\n👤 Enviado por: *{user_name}*{date_txt}{LINKS_FOOTER}"
            if p.get('url'):
                send_wa_image(p['url'], msg)
            else:
                send_wa_message(msg)

# 3. GATILHO: NOVA SUGESTÃO
@firestore_fn.on_document_created(document="suggestions/{suggestionId}")
def on_suggestion_created(event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None]) -> None:
    s = event.data.to_dict()
    if s:
        song = s.get('song', 'Desconhecida')
        artist = s.get('artist', 'Desconhecido')
        user = s.get('by', 'Alguém')
        yt_link = s.get('youtube', '')
        yt_txt = f"\n🎥 *Vídeo:* {yt_link}" if yt_link else ""
        msg = f"🎸 *Nova Sugestão de Música!*\n\n🎵 *Música:* {song}\n👤 *Artista:* {artist}\n✍️ *Sugerido por:* {user}{yt_txt}{LINKS_FOOTER}"
        
        # Se tiver link do YouTube, tenta pegar o thumbnail
        if yt_link:
            yt_id = extract_youtube_id(yt_link)
            if yt_id:
                thumb_url = f"https://img.youtube.com/vi/{yt_id}/hqdefault.jpg"
                send_wa_image(thumb_url, msg)
                return
        
        send_wa_message(msg)

# 4. GATILHO: LOGS (REMOÇÃO OU DISPARO MANUAL)
@firestore_fn.on_document_created(document="logs/{logId}")
def on_log_created(event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None]) -> None:
    log = event.data.to_dict()
    if not log: return

    action = log.get('action')
    log_id = event.params.get("logId") if getattr(event, "params", None) else None

    # A. Remoção de Sugestão
    if action == "Sugestão Removida":
        song = log.get('song', 'Música')
        artist = log.get('artist', 'Artista')
        suggested_by = log.get('by', 'Membro')
        likes = log.get('likes', 0)
        dislikes = log.get('dislikes', 0)
        removed_by = log.get('removedBy', 'Sistema')
        reason = str(log.get('reason') or 'Não informado').strip()
        if removed_by == 'Sistema' and dislikes >= 3:
            reason = 'Atingiu o limite de 3 dislikes'
        
        msg = (
            f"🗑️ *SUGESTÃO REMOVIDA*\n\n"
            f"🎵 *Música:* {song} - {artist}\n"
            f"👤 *Sugerida por:* {suggested_by}\n"
            f"📊 *Votos:* 👍 {likes} | 👎 {dislikes}\n"
            f"📝 *Motivo:* {reason}\n"
            f"👤 *Removido por:* {removed_by}\n\n"
            f"✨ *Não desanime, {suggested_by}!* O rock é feito de persistência. Se sua música não entrou agora, "
            f"tente sugerir novamente em um momento mais oportuno. Continuem participando!"
            f"{LINKS_FOOTER}"
        )
        result = send_wa_message(msg)
        update_log_delivery_status(firestore.client(), log_id, "sent" if result["ok"] else "failed", result["detail"])

    # B. Disparo Manual da Lista de Ensaio
    elif action == "Disparar Zap Ensaio":
        db = firestore.client()
        doc = db.collection("setlists").document("data").get()
        if doc.exists:
            tab0 = doc.to_dict().get("tab0", [])
            if tab0:
                sat_date = get_next_saturday_str()
                txt = "\n".join([f"{i+1}. {m.get('song')} ({m.get('artist')})" for i, m in enumerate(tab0)])
                result = send_wa_message(f"🎸 *LISTA DO ENSAIO — SÁBADO ({sat_date})*\n\n{txt}\n\nEstudem, pessoal! 🤘{LINKS_FOOTER}")
            else:
                result = send_wa_message(f"⚠️ *Atenção:* A lista do Ensaio Atual está vazia no momento.{LINKS_FOOTER}")
        else:
            result = send_wa_message(f"⚠️ *Erro:* Documento de setlist não encontrado.{LINKS_FOOTER}")
        update_log_delivery_status(db, log_id, "sent" if result["ok"] else "failed", result["detail"])

    # C. Cancelamento de Ensaio
    elif action == "Cancelar Ensaio":
        db = firestore.client()
        sat_date = get_next_saturday_str()
        sat_iso = get_next_saturday_iso()
        reason = str(log.get('reason') or log.get('detail') or 'Motivo não informado').strip()
        
        try:
            db.collection("rehearsal_state").document("current").set({
                "cancelled_date": sat_iso,
                "reason": reason,
                "updated_at": firestore.SERVER_TIMESTAMP
            })
            archived_forums = archive_rehearsal_forum(db, sat_iso)
            print(f"Fóruns arquivados no cancelamento de {sat_iso}: {archived_forums}")
            
            msg = (
                f"🚫 *AVISO IMPORTANTE: ENSAIO CANCELADO*\n\n"
                f"Informamos que *não teremos ensaio* neste próximo sábado ({sat_date}).\n\n"
                f"📝 *Motivo:* {reason}\n\n"
                f"Aproveitem o descanso e continuem praticando em casa! 🎸🤘"
                f"{LINKS_FOOTER}"
            )
            result = send_wa_message(msg)
            update_log_delivery_status(db, log_id, "sent" if result["ok"] else "failed", result["detail"])
        except Exception as exc:
            error_detail = f"{type(exc).__name__}: {exc}"[:300]
            print(f"Erro ao processar cancelamento de ensaio: {error_detail}")
            update_log_delivery_status(db, log_id, "failed", error_detail)

# 5. AGENDAMENTO: LEMBRETE DIÁRIO (14:10)
@scheduler_fn.on_schedule(schedule="10 14 * * *", timezone="America/Sao_Paulo")
def daily_reminder(event: scheduler_fn.ScheduledEvent) -> None:
    send_wa_message(f"📢 *Lembrete:* Não esqueça de votar nas enquetes de hoje!{LINKS_FOOTER}")

# 6. AGENDAMENTO: REPERTÓRIO (TERÇA ÀS 14:00)
@scheduler_fn.on_schedule(schedule="0 14 * * 2", timezone="America/Sao_Paulo")
def tuesday_repertoire(event: scheduler_fn.ScheduledEvent) -> None:
    db = firestore.client()
    
    # Verifica se o ensaio desta semana está cancelado
    sat_iso = get_next_saturday_iso()
    if is_rehearsal_cancelled(db, sat_iso):
        print(f"Cancelando disparo automático: ensaio de {sat_iso} está marcado como cancelado.")
        return

    doc = db.collection("setlists").document("data").get()
    if doc.exists:
        tab0 = doc.to_dict().get("tab0", [])
        if tab0:
            sat_date = get_next_saturday_str()
            txt = "\n".join([f"{i+1}. {m.get('song')} ({m.get('artist')})" for i, m in enumerate(tab0)])
            send_wa_message(f"🎸 *REPERTÓRIO DO ENSAIO — SÁBADO ({sat_date})*\n\n{txt}\n\nEstudem! 🤘{LINKS_FOOTER}")

# 7. AGENDAMENTO: ABRIR FÓRUM DO ENSAIO (SÁBADO 00:01)
@scheduler_fn.on_schedule(schedule="1 0 * * 6", timezone="America/Sao_Paulo")
def open_rehearsal_forum(event: scheduler_fn.ScheduledEvent) -> None:
    db = firestore.client()
    sat_iso = get_next_saturday_iso()
    sat_str = get_next_saturday_str()

    if is_rehearsal_cancelled(db, sat_iso):
        print(f"Fórum automático não criado: ensaio de {sat_iso} está cancelado.")
        return

    created = ensure_rehearsal_forum(db, sat_iso, sat_str)
    print(f"Fórum automático {'criado' if created else 'já existente'} para o ensaio de {sat_iso}.")

# 8. AGENDAMENTO: ENCERRAR FÓRUM DO ENSAIO (SÁBADO 23:59)
@scheduler_fn.on_schedule(schedule="59 23 * * 6", timezone="America/Sao_Paulo")
def close_rehearsal_forum(event: scheduler_fn.ScheduledEvent) -> None:
    db = firestore.client()
    sat_iso = get_current_saturday_iso()
    close_count = archive_rehearsal_forum(db, sat_iso)
    print(f"{close_count} fórum(ns) encerrado(s) para o ensaio de {sat_iso}.")

# 9. AGENDAMENTO: MONITOR DE ENQUETES (CADA 1 HORA)
@scheduler_fn.on_schedule(schedule="0 * * * *", timezone="America/Sao_Paulo")
def poll_monitor(event: scheduler_fn.ScheduledEvent) -> None:
    db = firestore.client()
    from datetime import timezone
    now = datetime.now(timezone.utc)

    # D. Garantir que a promoção automática avance mesmo sem ninguém abrir o site.
    try:
        advance_promotion_pipeline(db)
    except Exception as exc:
        print(f"Erro no pipeline automático de promoção: {type(exc).__name__}: {exc}")
    
    # A. Notificar Encerramento (Enquetes que acabaram de expirar)
    expired = db.collection("polls").where("deadline", ">", (now - timedelta(minutes=60)).isoformat()).where("deadline", "<=", now.isoformat()).stream()
    for doc in expired:
        p = doc.to_dict()
        opts = p.get("options", [])
        if not opts: continue
        res = sorted(opts, key=lambda x: x.get('votes', 0), reverse=True)
        winner = res[0].get('label')
        t = p.get("type", "")
        if t in ["repertoire", "repertory"]:
            send_wa_message(build_repertory_result_message(p))
        elif t in ["promotion", "tiebreaker"]:
            send_wa_message(build_tiebreaker_result_message(db, p))

    # B. Notificar Faltando 24 Horas
    expiring_24h = db.collection("polls").where("deadline", ">", (now + timedelta(hours=23)).isoformat()).where("deadline", "<=", (now + timedelta(hours=24)).isoformat()).stream()
    for doc in expiring_24h:
        p = doc.to_dict()
        q = p.get("question", "Enquete")
        send_wa_message(f"⏳ *FALTAM 24 HORAS!*\n\nA enquete *\"{q}\"* encerra amanhã. Já deixou seu voto?{LINKS_FOOTER}")

    # C. Notificar Faltando 1 Hora
    expiring_1h = db.collection("polls").where("deadline", ">", now.isoformat()).where("deadline", "<=", (now + timedelta(hours=1)).isoformat()).stream()
    for doc in expiring_1h:
        p = doc.to_dict()
        q = p.get("question", "Enquete")
        send_wa_message(f"⚠️ *ÚLTIMA CHAMADA (1 HORA)!*\n\nA enquete *\"{q}\"* encerra em breve. Corre lá para votar!{LINKS_FOOTER}")
